name: Command-Line Interface CI

on:
  push:
    branches-ignore: 'main'
    paths:
      - 'packages/Comfyg.Cli/**'
      - 'packages/Comfyg.Client/**'
      - 'tests/Comfyg.Client.Tests/**'
  pull_request:
    paths:
      - 'packages/Comfyg.Cli/**'
      - 'packages/Comfyg.Client/**'
      - 'tests/Comfyg.Client.Tests/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '7.0.x', '6.0.x' ]
    name: .NET ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
          dotnet test tests/Comfyg.Cli.Tests
          dotnet test tests/Comfyg.Client.Tests
  Build:
    needs: Test
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest', 'macos-latest' ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
            6.0.x
      - run: dotnet pack -p:PackageOutputPath=nuget
      - uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: nuget
