name: Comfyg CI

on:
  push:
    branches-ignore: 'main'
    paths:
      - 'packages/Comfyg/**'
      - 'packages/Comfyg.Client/**'
      - 'tests/Comfyg.Tests/**'
      - 'tests/Comfyg.Client.Tests/**'
  pull_request:
    paths:
      - 'packages/Comfyg/**'
      - 'packages/Comfyg.Client/**'
      - 'tests/Comfyg.Tests/**'
      - 'tests/Comfyg.Client.Tests/**'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '7.0.x', '6.0.x' ]
    name: .NET ${{ matrix.dotnet }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
          dotnet test ./tests/Comfyg.Tests
          dotnet test ./tests/Comfyg.Client.Tests
