name: Documentation CD

on:
  push:
    branches: 'main'
    paths:
      - 'docs/**'
      - '.github/workflows/docs-cd.yml'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x
      - run: dotnet tool uninstall -g docfx
      - run: dotnet tool install -g docfx --version 2.63.1
      - run: docfx docs/docfx.json
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_site
  Publish:
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
