name: Documentation CD

on:
  push:
    branches: 'main'
    paths:
      - 'docs/**'
      - '.github/workflows/docs-cd.yml'

# TODO: use dotnet swagger tofile

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - run: dotnet publish -c Release packages/Store/Comfyg.Store.Api/Comfyg.Store.Api.csproj
      - run: dotnet tool restore
      - run: dotnet tool install -g docfx --version 2.63.1
      - run: dotnet swagger tofile --serializeasv2 --output docs/swagger.json packages/Store/Comfyg.Store.Api/bin/Release/net6.0/publish/Comfyg.Store.Api.dll v1
      - run: docfx docs/docfx.json
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs/_site
  Publish:
    needs: Build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment
